pipeline {
    agent any

    stages {
        stage('checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/nagabhushanamn/batch1-repo'
            }
        }
        stage('install dependencies') {
            steps {
                echo 'install dependencies..'
            }
        }
        stage('building') {
            steps {
                echo 'building....'
            }
        }
        stage('test') {
            steps {
                echo 'testing....'
            }
        }
         stage('deploy') {
            steps {
                echo 'deploying....'
            }
        }
    }
}