pipeline {
    
    agent any

    stages {

        stage('git-checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/nagabhushanamn/batch1-repo'
            }
        }

        stage('install dependencies') {
            steps {
                dir("ui"){
                    sh 'npm i'
                }
            }
        }

        stage('test') {
            steps {
                 sh 'npm run test'
            }
        }

        stage('building') {
            steps {
                dir("ui"){
                    sh 'npm run build'
                }
            }
        }
       
        stage('deploy') {
            steps {
                dir("ui"){
                    input('deploy?')
                    sh 'scp -r build/ root@165.22.217.249:/var/'
                }
            }
        }

    }
}