pipeline {
    agent any

    stages {
        stage('checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/nagabhushanamn/batch1-repo'
            }
        }
        stage('install dependencies') {
            steps {
                dir("ui"){
                    sh 'npm i'
                }
            }
        }
        stage('building') {
            steps {
                dir("ui"){
                    sh 'npm run build'
                }
            }
        }
        stage('test') {
            steps {
                echo 'testing....'
            }
        }
         stage('deploy') {
            steps {
                dir("ui"){
                }
            }
        }
    }
}